package com.iab.gdpr;

public interface ConsentStringConstants {
	int VENDOR_ENCODING_RANGE = 1;

	int VERSION_BIT_OFFSET = 0;
	int VERSION_BIT_SIZE = 6;
	int CREATED_BIT_OFFSET = 6;
	int CREATED_BIT_SIZE = 36;
	int UPDATED_BIT_OFFSET = 42;
	int UPDATED_BIT_SIZE = 36;
	int CMP_ID_OFFSET = 78;
	int CMP_ID_SIZE = 12;
	int CMP_VERSION_OFFSET = 90;
	int CMP_VERSION_SIZE = 12;
	int CONSENT_SCREEN_SIZE_OFFSET = 102;
	int CONSENT_SCREEN_SIZE = 6;
	int CONSENT_LANGUAGE_OFFSET = 108;
	int CONSENT_LANGUAGE_SIZE = 12;
	int VENDOR_LIST_VERSION_OFFSET = 120;
	int VENDOR_LIST_VERSION_SIZE = 12;
	int PURPOSES_OFFSET = 132;
	int PURPOSES_SIZE = 24;
	int MAX_VENDOR_ID_OFFSET = 156;
	int MAX_VENDOR_ID_SIZE = 16;
	int ENCODING_TYPE_OFFSET = 172;
	int ENCODING_TYPE_SIZE = 1;
	int VENDOR_BITFIELD_OFFSET = 173;
	int DEFAULT_CONSENT_OFFSET = 173;
	int NUM_ENTRIES_OFFSET = 174;
	int NUM_ENTRIES_SIZE = 12;
	int RANGE_ENTRY_OFFSET = 186;
	int VENDOR_ID_SIZE = 16;
}
